export { isTruthy } from './isTruthy';
export { isFalsy } from './isFalsy';
export { hasProperty } from './hasProperty';
export { equals, strictEquals, subsetEquals } from './equals';
export { contains } from './contains';
export { containsMatch } from './containsMatch';
export { containsMatches } from './containsMatches';
export { isEither } from './isEither';
export { isError } from './isError';
export { isOption } from './isOption';
export { isThese } from './isThese';
export { isEitherOrThese } from './isEitherOrThese';
export { isValidation } from './isValidation';
export { matches } from './matches';
