export { isTruthy } from './isTruthy';
export { isFalsy } from './isFalsy';
export { hasProperty } from './hasProperty';
export { equals, strictEquals, subsetEquals } from './equals';
export { matches } from './matches';
export { matchesObject } from './matchesObject';
export { contains } from './contains';
export { containsMatch } from './containsMatch';
export { containsMatches } from './containsMatches';
export { applyPredicate, applyPredicateLeft } from '../either/applyPredicate';
export { isEither } from './isEither';
