name: Build

on:
  pull_request:
  push:
    branches:
      - main

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: '16'

      - name: Checkout
        uses: actions/checkout@v3

      - name: Install
        run: npm ci --ignore-scripts

      - name: Lint
        run: npm run lint:check

      - name: Prettier
        run: npm run prettier:check

      - name: Test
        run: npm test

      - name: Build
        run: npm run build
